(add-hook 'emacs-lisp-mode-hook       (lambda ()
					(eldoc-mode t)
					(paredit-mode t)
					(rainbow-delimiters-mode t)))
(add-hook 'eval-expression-minibuffer-setup-hook 'paredit-mode)
(add-hook 'ielm-mode-hook             #'enable-paredit-mode)
(add-hook 'lisp-mode-hook             #'enable-paredit-mode)
(add-hook 'lisp-interaction-mode-hook (lambda ()
					(rainbow-delimiters-mode t)
                                        (paredit-mode t)
					(eldoc-mode t)
                                        (define-key lisp-interaction-mode-map (kbd "M-j") 'eval-print-last-sexp)))
(add-hook 'scheme-mode-hook 'paredit-mode)
(add-hook 'ielm-mode-hook 'eldoc-mode)
