(key-chord-mode t)

(eval-after-load "yasnippet" #'(progn
				 (define-key yas-minor-mode-map (kbd "C-i") nil)
				 (define-key yas-minor-mode-map (kbd "<tab>") nil)
				 (define-key yas-minor-mode-map (kbd "TAB") nil)))
(eval-after-load "yasnippet" #'(progn
				 (define-key company-mode-map (kbd "C-h") nil)
				 (define-key company-mode-map (kbd "M-p") nil)
				 (define-key company-mode-map (kbd "M-n") nil)
				 (define-key company-mode-map (kbd "C-SPC") #'company-select-next)
				 (define-key company-mode-map (kbd "S-SPC") #'company-select-previous)))
(global-set-key (kbd "s-i")  #'indent-buffer)
(global-set-key (kbd "s-o") #'er/expand-region)
(global-set-key (kbd "C-o") #'ido-find-file)
(global-set-key (kbd "C-f") #'isearch-forward)
(global-set-key (kbd "C-S-f") #'isearch-backward)
(global-set-key (kbd "C-p") #'yas-ido-expand)
(global-set-key (kbd "C-c k" ) #'delete-this-buffer-and-file)
(global-set-key (kbd "C-w") #'cut-line-or-region)
(global-set-key (kbd "M-w") #'copy-line-or-region)
(global-set-key (kbd "C-z") #'undo)
(global-set-key (kbd "C-v") 'yank)
(global-set-key (kbd "C-s") 'save-buffer)
(global-set-key (kbd "C-S-s") 'write-file)
(global-set-key (kbd "C-k") #'next-line)
(global-set-key (kbd "<f8>") #'execute-extended-command)
(global-set-key (kbd "<f9>") #'magit-status)
(global-set-key (kbd "C-i") #'previous-line)
(global-set-key (kbd "C-j") #'backward-char)
(global-set-key (kbd "C-l") #'forward-char)
(global-set-key (kbd "C-n") #'newline-and-indent)
(global-set-key (kbd "C-<right>") #'sp-forward-slurp-sexp)
(global-set-key (kbd "C-<left>") #'sp-backward-slurp-sexp)
(global-set-key (kbd "C-<up>") #'sp-add-to-previous-sexp)
(global-set-key (kbd "C-<down>") #'sp-add-to-next-sexp)
(global-set-key (kbd "C->") #'mc/mark-next-like-this)
(global-set-key (kbd "C-<") #'mc/mark-previous-like-this)
(global-set-key (kbd "C-S-d") #'duplicate-current-line)
(global-set-key (kbd "s-SPC") #'set-mark-command)
(global-set-key (kbd "M-a") #'mark-whole-buffer)
(global-set-key (kbd "S-C-<left>") #'shrink-window-horizontally)
(global-set-key (kbd "S-C-<right>") #'enlarge-window-horizontally)
(global-set-key (kbd "S-C-<down>") #'shrink-window)
(global-set-key (kbd "S-C-<up>") #'enlarge-window)
(global-set-key (kbd "C-h") #'sp-backward-delete-char)
(global-set-key (kbd "M-d") #'sp-kill-word)
(global-set-key (kbd "M-h") #'sp-backward-kill-word)
(global-set-key (kbd "C-d") #'sp-delete-char)
(global-set-key (kbd "C-S-k") #'sp-kill-hybrid-sexp)
(global-set-key (kbd "C-;") #'comment-line)
(global-set-key (kbd "<f6>") #'imenu)
